In [15]:
import requests
import holoviews as hv
import pandas as pd
import numpy as np
pd.options.plotting.backend = 'holoviews'
%matplotlib inline

In [65]:
def get_crypto(start_date="1/1/2020",
    end_date="3/1/2020",
    crypto="BTC-USD"):
    rest_api_str = f'https://api.pro.coinbase.com/products/{crypto}/candles?start="{start_date}"&end="{end_date}"&granularity=86400'
    response = requests.get(rest_api_str)
    crypto_df = pd.DataFrame(response.json())
    crypto_df=crypto_df.iloc[:,[0,4,5]]
    crypto_df.columns=['date','close','volume']
    crypto_df["date"] = pd.to_datetime(crypto_df["date"], unit='s')
    
    
    return crypto_df
    
#rest_api_str = f'https://api.pro.coinbase.com/products/{crypto}/candles?start="{start_date}"&end="{end_date}"&granularity=86400'

In [66]:
get_crypto()

         date    close        volume
0  2020-03-01  8522.31   7353.139605
1  2020-02-29  8525.07   5142.708305
2  2020-02-28  8708.89  13643.285903
3  2020-02-27  8812.49  14781.020203
4  2020-02-26  8778.30  21610.462900
..        ...      ...           ...
56 2020-01-05  7355.40   5942.014946
57 2020-01-04  7348.63   4742.466210
58 2020-01-03  7334.45  14056.392385
59 2020-01-02  6945.02   8010.927387
60 2020-01-01  7174.33   3350.630049

[61 rows x 3 columns]

In [71]:
get_crypto('01/01/2019','03/01/2019', 'ETH-USD')

         date   close         volume
0  2019-03-01  134.72   90382.888794
1  2019-02-28  134.48  118030.516585
2  2019-02-27  134.46  149133.384471
3  2019-02-26  135.66   94611.606741
4  2019-02-25  137.64  165457.690974
5  2019-02-24  131.76  349219.944052
6  2019-02-23  157.56  169420.225773
7  2019-02-22  146.68   82908.850850
8  2019-02-21  144.21  114594.169263
9  2019-02-20  147.19  142484.555051
10 2019-02-19  142.69  174940.353324
11 2019-02-18  144.62  324838.344456
12 2019-02-17  132.34  189286.818240
13 2019-02-16  121.56   37397.103038
14 2019-02-15  120.42   62036.488688
15 2019-02-14  119.39   74312.954582
16 2019-02-13  120.74   91230.803477
17 2019-02-12  120.82  104451.636629
18 2019-02-11  119.55  126354.217158
19 2019-02-10  123.94   93443.533887
20 2019-02-09  118.06   67741.852037
21 2019-02-08  117.96  232502.282622
22 2019-02-07  103.21   47915.938889
23 2019-02-06  103.36  106516.796066
24 2019-02-05  106.00   41040.000115
25 2019-02-04  106.08   45781.087506
26 2019-02-03  105.94   65945.943248
27 2019-02-02  109.30   58843.402308
28 2019-02-01  105.88   88491.116490
29 2019-01-31  105.79   85581.121915
30 2019-01-30  107.61  111443.141351
31 2019-01-29  104.02   77500.924183
32 2019-01-28  105.47  175738.308720
33 2019-01-27  111.35   70799.343083
34 2019-01-26  115.01   43621.343854
35 2019-01-25  114.95   77821.190920
36 2019-01-24  116.40   59367.657072
37 2019-01-23  116.55   61060.321897
38 2019-01-22  118.08  124950.907693
39 2019-01-21  115.86   84283.268499
40 2019-01-20  117.43   96855.286625
41 2019-01-19  123.17   90928.963083
42 2019-01-18  119.53   65948.754831
43 2019-01-17  122.55  117990.758196
44 2019-01-16  122.12  148908.690966
45 2019-01-15  120.00  201834.223669
46 2019-01-14  128.37  203574.726320
47 2019-01-13  115.58  145212.547894
48 2019-01-12  124.59   88962.939987
49 2019-01-11  125.83  161522.398568
50 2019-01-10  126.41  346632.619689
51 2019-01-09  149.50   94953.111019
52 2019-01-08  148.97  123724.633999
53 2019-01-07  150.62  145179.871486
54 2019-01-06  155.92  173438.862199
55 2019-01-05  154.21  213686.162767
56 2019-01-04  153.24  220512.570702
57 2019-01-03  147.23  197122.585993
58 2019-01-02  153.50  238326.551039
59 2019-01-01  139.75  157652.410085

In [80]:
get_crypto('01/01/2019','03/01/2019','LTC-USD')

         date  close         volume
0  2019-03-01  46.81  211111.570729
1  2019-02-28  45.44  197200.504710
2  2019-02-27  44.96  204553.878308
3  2019-02-26  44.66  128690.144230
4  2019-02-25  45.37  269628.580380
5  2019-02-24  43.57  577755.259645
6  2019-02-23  51.19  244480.292419
7  2019-02-22  49.07  164043.944009
8  2019-02-21  48.46  234935.876587
9  2019-02-20  51.08  366447.369287
10 2019-02-19  46.91  281079.423140
11 2019-02-18  47.34  522009.972289
12 2019-02-17  43.45  190497.599284
13 2019-02-16  43.15  144989.790578
14 2019-02-15  42.08  191649.449898
15 2019-02-14  40.93  137448.235664
16 2019-02-13  41.21  215077.491189
17 2019-02-12  43.35  188035.753045
18 2019-02-11  42.37  314108.280477
19 2019-02-10  46.51  335347.482233
20 2019-02-09  44.20  386221.374252
21 2019-02-08  42.56  832038.604085
22 2019-02-07  32.85   74760.782304
23 2019-02-06  32.47  166097.872206
24 2019-02-05  33.95   92003.981901
25 2019-02-04  33.64  116895.845692
26 2019-02-03  32.87  186816.581466
27 2019-02-02  34.18  153214.289349
28 2019-02-01  32.37  190732.776292
29 2019-01-31  31.24   98659.785182
30 2019-01-30  31.53  112873.999443
31 2019-01-29  30.69   89350.181281
32 2019-01-28  30.96  198306.907923
33 2019-01-27  32.02  101485.403828
34 2019-01-26  32.64  146096.815414
35 2019-01-25  32.73  147988.898339
36 2019-01-24  32.47  139317.911985
37 2019-01-23  31.60   99821.381820
38 2019-01-22  31.48  179720.992599
39 2019-01-21  30.82   87793.675603
40 2019-01-20  30.61  162111.496618
41 2019-01-19  32.22  115529.853975
42 2019-01-18  30.96   81934.510294
43 2019-01-17  31.62  164225.694321
44 2019-01-16  31.40  103454.769987
45 2019-01-15  30.99  181171.817608
46 2019-01-14  32.07  186937.972494
47 2019-01-13  29.92  254441.289091
48 2019-01-12  32.04  112850.542081
49 2019-01-11  31.79  254559.771567
50 2019-01-10  33.27  468509.008680
51 2019-01-09  38.58  168060.729040
52 2019-01-08  39.13  370547.436060
53 2019-01-07  37.71  239703.649702
54 2019-01-06  38.88  459249.463757
55 2019-01-05  34.48  352630.878429
56 2019-01-04  32.02  140520.872781
57 2019-01-03  31.60  116386.060027
58 2019-01-02  32.94  149356.693330
59 2019-01-01  31.68  163841.181845

In [81]:
get_crypto('01/01/2019','03/01/2019','ETC-USD')

         date  close         volume
0  2019-03-01   4.58   35031.152781
1  2019-02-28   4.55   29983.448064
2  2019-02-27   4.58   34042.116340
3  2019-02-26   4.63   33635.968015
4  2019-02-25   4.63   50302.005558
5  2019-02-24   4.74  182551.787503
6  2019-02-23   4.85  117462.389748
7  2019-02-22   4.69   95333.913449
8  2019-02-21   4.47   73210.817087
9  2019-02-20   4.64  106843.920120
10 2019-02-19   4.57  196504.263942
11 2019-02-18   4.38  176375.462558
12 2019-02-17   4.16   65957.508545
13 2019-02-16   4.12   37548.356399
14 2019-02-15   4.07   53497.301817
15 2019-02-14   4.10   40727.046182
16 2019-02-13   4.08   30576.295779
17 2019-02-12   4.06   69803.013285
18 2019-02-11   4.02   63324.615298
19 2019-02-10   4.16   58680.071888
20 2019-02-09   4.06   62981.336503
21 2019-02-08   4.08  157331.539376
22 2019-02-07   3.79   39067.719526
23 2019-02-06   3.70   90812.084716
24 2019-02-05   3.84   29900.463870
25 2019-02-04   3.83   28853.056941
26 2019-02-03   3.85   43537.964508
27 2019-02-02   3.95   35948.083065
28 2019-02-01   3.89   51986.476134
29 2019-01-31   3.90   57129.194304
30 2019-01-30   3.95  104524.045011
31 2019-01-29   3.89   66030.011554
32 2019-01-28   3.96  237656.271037
33 2019-01-27   4.32   21810.682413
34 2019-01-26   4.36   38157.421843
35 2019-01-25   4.36   34879.811770
36 2019-01-24   4.39   29038.165574
37 2019-01-23   4.35   43924.949950
38 2019-01-22   4.39   42027.896966
39 2019-01-21   4.37   26135.066404
40 2019-01-20   4.39   38549.360869
41 2019-01-19   4.46   34916.386463
42 2019-01-18   4.45   26529.380234
43 2019-01-17   4.49   29863.515590
44 2019-01-16   4.46   36268.407572
45 2019-01-15   4.40   52727.850546
46 2019-01-14   4.50   67014.722346
47 2019-01-13   4.35   62195.909412
48 2019-01-12   4.57   80304.828582
49 2019-01-11   4.63  110479.594979
50 2019-01-10   4.57  196590.534200
51 2019-01-09   4.97  119834.809163
52 2019-01-08   4.97  209070.159283
53 2019-01-07   5.01  263996.904192
54 2019-01-06   5.45  214334.353884
55 2019-01-05   5.11   97301.175260
56 2019-01-04   5.22  146154.237284
57 2019-01-03   5.03  178279.793753
58 2019-01-02   5.35  188077.811093
59 2019-01-01   5.25  165373.560364